#!/bin/bash

command="$1"
case "${command}" in
  clean)
      find . -type d -name bin -exec rm -r {} \;
      find . -type d -name obj -exec rm -r {} \;
      rm -r ./packages/*
      rm -r ./paket-files/*
      rm -r ./nuget-packages/*
      ;;
  _build)
      # restore packages and build the whole solution
      dotnet publish --configuration=Release --output=./bin/Release
      exit $?
      ;;
  build)
      dojo "./tasks _build"
      exit $?
      ;;
  _run)
      # TODO: add --no-build so that we do not recreate the artifacts
      dotnet run --configuration=Release --project=./src/app/
      exit $?
      ;;
  run)
      dojo "./tasks _run"
      exit $?
      ;;
  _unit)
      tests=$(set -x; dotnet test --configuration=Release --no-build --list-tests ./tests/app.Tests)
      if [[ "${tests}" == "" ]]; then
        echo "No tests found"
        exit 1
      fi
      # this task does NOT compile the test project
      dotnet test --configuration=Release --no-build ./tests/app.Tests
      exit $?
      ;;
  unit)
      dojo "./tasks _unit"
      exit $?
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
