version: 2.1

workflows:
  dotnet-example:
    jobs:
      - compile
      - unit:
          requires:
            - compile

jobs:
  compile:
    executor: platform
    steps:
      - setup
      - run:
          command: dojo "dotnet publish --configuration=Release --output=./bin/Release"

  unit:
    executor: platform
    steps:
      - setup
      - run:
          command: dojo "dotnet test --configuration=Release ./tests/app.Tests"


commands:
  setup:
    steps:
      - checkout

executors:
  platform:
    machine:
      image: ubuntu-2004:202101-01
    working_directory: ~/repo
