version: 2.1

workflows:
  dotnet-example:
    jobs:
      - build
      - unit:
          requires:
            - build
      - run:
          requires:
            - unit

jobs:
  build:
    executor: platform
    steps:
      - setup
      - run:
          command: ./tasks build

  unit:
    executor: platform
    steps:
      - setup
      - run:
          command: ./tasks unit

  run:
    executor: platform
    steps:
      - setup
      - run:
          command: ./tasks run


commands:
  setup:
    steps:
      - checkout
      - run:
          name: Install dojo
          command: |
            version="0.11.0"
            wget -O /tmp/dojo https://github.com/kudulab/dojo/releases/download/${version}/dojo_linux_amd64
            chmod +x /tmp/dojo
            sudo mv /tmp/dojo /usr/bin/dojo

executors:
  platform:
    machine:
      image: ubuntu-2004:202101-01
    working_directory: ~/repo
