version: 2.1

workflows:
  docker-dotnet-dojo:
    jobs:
      - compile
      - unit:
          requires:
            - compile

jobs:
  compile:
    executor: platform
    steps:
      - setup
      - run:
          command: dojo "dotnet publish --configuration=Release --output=./bin/Release"

  unit:
    executor: platform
    steps:
      - setup
      - run:
          command: dojo "dotnet test --configuration=Release ./tests/app.Tests"
